{% set name = "bullet" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "dfa0fa81810ad1a9e688815ca04f24af87ff5cdbe803b42fa634b1f50fc9d887"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - bullet

about:
  home: "https://github.com/Mckinsey666/bullets"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Beautiful Python prompts made simple."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - oblute
