{% set name = "ecctl" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elastic/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 12c99e715b114df583e172bee3ffc81a90802b7801f3326b827f204e0d5e3605

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - make

test:
  requires:
    - m2-bash       # [win]
    - m2-coreutils  # [win]

  commands:
    - ecctl deployment list

about:
  home: https://www.elastic.co/guide/en/ecctl/current/index.html
  license: Apache-2.0
  license_file: LICENSE
  summary: ecctl is the CLI for the Elasticsearch Service and Elastic Cloud Enterprise APIs.
  doc_url: https://www.elastic.co/guide/en/ecctl/current/index.html
  dev_url: https://github.com/elastic/{{ name }}

extra:
  recipe-maintainers:
    - oblute
