{% set name = "sagemaker-tensorflow-extensions" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 63c2382dfc042a2d317f99fcf973fed904782759fc1bb4a112479fcb5459b16e
  patches:
    - setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [(py27) or (win)]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - libcurl
    - curl
    - tensorflow >=1.7
    - sagemaker-python-sdk
    - setuptools
    - boto3
    - docker-compose
  host:
    - python
    - pip
    - setuptools
    - libcurl
    - curl
    - tensorflow >=1.7
    - sagemaker-python-sdk
    - boto3
    - docker-compose
    - zlib
  run:
    - python
    - setuptools
    - libcurl
    - curl
    - tensorflow >=1.7
    - sagemaker-python-sdk
    - boto3
    - docker-compose
    - zlib

test:
  requires:
    - tox
    - flake8
    - pytest
    - sagemaker-python-sdk
    - docker-compose
    - boto3
    - mock
  imports:
    - sagemaker_tensorflow

about:
  home: https://github.com/aws/sagemaker-tensorflow-extensions
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Amazon Sagemaker specific TensorFlow extensions."
  doc_url: https://sagemaker.readthedocs.io/en/stable/using_tf.html
  dev_url: https://github.com/aws/sagemaker-tensorflow-extensions

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - benhuff
