{% set name = "tensorflow-addons" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/addons/archive/v{{ version }}.tar.gz
  sha256: 6c003745ac7cc371bebc6e625617d265c9767c841e5ecb8627c08823357548f7

build:
  number: 0
  script:
    - rm -f BUILD
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - tensorflow-base ==2.0.0
    - setuptools
    - six >= 1.10.0
  run:
    - python
    - tensorflow-base ==2.0.0
    - setuptools
    - six >= 1.10.0

test:
  imports:
    - tensorflow_addons

about:
  home: https://www.tensorflow.org/addons
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'TensorFlow Addons is a repository of contributions that conform to well-established API patterns'
  description: |
    TensorFlow Addons is a repository of contributions that conform to
    well-established API patterns, but implement new functionality not
    available in core TensorFlow. TensorFlow natively supports a large
    number of operators, layers, metrics, losses, and optimizers.
    However, in a fast moving field like ML, there are many interesting new
    developments that cannot be integrated into core TensorFlow (because
    their broad applicability is not yet clear, or it is mostly used by
    a smaller subset of the community).
  doc_url: https://www.tensorflow.org/addons
  dev_url: https://github.com/tensorflow/addons

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - benhuff
