{% set name = "tensorflow-addons" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tensorflow/addons/archive/v{{ version }}.tar.gz
  sha256: e6bfe8f1c826f3fb04db636b677a51565ad603e9f96a5aaf858f7fa51d729961

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - tensorflow
    - typeguard >=2.7

test:
  imports:
    - tensorflow_addons

about:
  home: https://github.com/tensorflow/addons
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow Addons is a repository of contributions that conform to well-established API patterns, but implement new functionality not available in core TensorFlow.
  doc_url: https://www.tensorflow.org/addons/api_docs/python/tfa
  dev_url: https://github.com/tensorflow/addons

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
