{% set name = "mariadb-c" %}
{% set version = "3.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mariadb-corporation/mariadb-connector-c/archive/v{{ version }}.tar.gz
  sha256: 2cd769afea447231588580234523121268eae7576f75a7bee25a7e6ec04282f8

build:
  number: 0
  skip: True  # [win]
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - test -f ${PREFIX}/include/mariadb/ma_io.h   # [unix]

about:
  home: https://github.com/mariadb-corporation/mariadb-connector-c
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING.LIB
  summary: MariaDB client library that can be used to connect to MySQL or MariaDB
  dev_url: https://github.com/mariadb-corporation/mariadb-connector-c

extra:
  recipe-maintainers:
    - oblute
